### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by iotech-fvtt** [MrXofar/compendium-navigator#2]
I dont see anywhere in Foundry to open this tool (yes, I have it activated in Module Management). Is there a button or macro I should be using?

**Comment by MrXofar** [comment]
Click on Compendium tab, then click the Compendium Navigator button. 
If you have Compendium Browser active, you won't see Compendium Navigator button - I plan on correcting that in the next update.
![image](https://user-images.githubusercontent.com/103948142/193720732-5796202a-be88-4cc5-8775-6e59326c10a5.png)

**Comment by iotech-fvtt** [comment]
Ah, I do have Compendium Browser so that explains it. Thanks!

**Comment by MrXofar** [comment]
Yeah, I'm not yet sure why it does that. But tbh I have not digged too deep into it yet.

Edit: Nevermind, I know why. it's silly really. You can fix locally if you want until I release update.

On main.js, on line 23 (of Compendium Navigator), remove **class="compendium-browser-btn"**

**Comment by iotech-fvtt** [comment]
I was just about to send you that! Thanks for the update, this is pretty sweet, especially the easy ability to make tables! Thanks for your work!

**Comment by MrXofar** [comment]
Thanks, glad you like it! I have a lot of refactoring and cleanup to do. After that I will add the other document types - among other features listed in [changes.txt](https://github.com/MrXofar/compendium-navigator/blob/master/changes.txt)
